<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13618" started-at="2016-03-06T08:55:11Z" finished-at="2016-03-06T08:55:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13618" started-at="2016-03-06T08:55:11Z" finished-at="2016-03-06T08:55:24Z">
      <class name="com.theGongzuo.pageObjects.AdvancedJobTest">
        <test-method status="PASS" signature="geturl()[pri:0, instance:com.theGongzuo.pageObjects.AdvancedJobTest@6e3c1e69]" name="geturl" is-config="true" duration-ms="6576" started-at="2016-03-06T00:55:11Z" finished-at="2016-03-06T00:55:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- geturl -->
        <test-method status="FAIL" signature="AdvancedJobTestT()[pri:0, instance:com.theGongzuo.pageObjects.AdvancedJobTest@6e3c1e69]" name="AdvancedJobTestT" duration-ms="7027" started-at="2016-03-06T00:55:17Z" finished-at="2016-03-06T00:55:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Keywords: Software Engineer] but found [Keyword: Software Engineer]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Keywords: Software Engineer] but found [Keyword: Software Engineer]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.theGongzuo.pageObjects.AdvancedJobTest.AdvancedJobTestT(AdvancedJobTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdvancedJobTestT -->
      </class> <!-- com.theGongzuo.pageObjects.AdvancedJobTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
